Home work #1

In [2]:
import numpy as np

In [3]:
#1
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
#2
a = np.zeros((3, 3), dtype=int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [5]:
#3
a = np.random.randint(1, 11, size=(5, 5))
print(a)

[[ 6 10  3 10  7]
 [ 8  5  2  6  5]
 [10 10  3  1  6]
 [ 4 10  9  4 10]
 [ 6  7 10  7  7]]


In [6]:
#4
a = np.random.uniform(low=0.0, high=1.0, size=(4, 4))
print(a)

[[0.94865901 0.9343477  0.17056601 0.51719184]
 [0.84627734 0.66250001 0.85374035 0.39879517]
 [0.84702082 0.55872248 0.17462187 0.47512723]
 [0.64704025 0.18172311 0.60191032 0.10006006]]


In [7]:
#5
a = np.random.randint(1, 11, size=(5))
b = np.random.randint(1, 11, size=(5))
print(a+b)
print(a-b)
print(a/b)

[12 13 17 11 16]
[-2 -5  1  9 -4]
[ 0.71428571  0.44444444  1.125      10.          0.6       ]


In [8]:
#6
a = np.random.random(7)
b = np.random.random(7)
print(np.dot(a, b))

1.8509112784197437


In [9]:
#7
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 3))
print(np.dot(a, b))

[[113 115  75]
 [ 76  84  52]]


In [10]:
#8
a = np.random.randint(1, 11, size=(3, 3))
a_inv = np.linalg.inv(a)
print(a)
print(a_inv)

[[ 3 10  2]
 [ 7  7  2]
 [ 6  4  7]]
[[-0.14909091  0.22545455 -0.02181818]
 [ 0.13454545 -0.03272727 -0.02909091]
 [ 0.05090909 -0.17454545  0.17818182]]


In [11]:
#9
a = np.random.randint(1, 11, size=(4, 4))
print(a)
print(a.T)

[[ 2  9 10  5]
 [ 3  1  4  9]
 [ 7  2  2  3]
 [ 1  8  4  2]]
[[ 2  3  7  1]
 [ 9  1  2  8]
 [10  4  2  4]
 [ 5  9  3  2]]


In [12]:
#10
a = np.random.randint(1, 11, size=(3, 4))
b = np.random.randint(1, 11, size=(4))
print(a)
print(b)
print(a * b)

[[ 2  9 10  7]
 [ 3  3  4  3]
 [10  4  2  9]]
[ 1 10  8  6]
[[ 2 90 80 42]
 [ 3 30 32 18]
 [10 40 16 54]]


In [13]:
#11
a = np.random.uniform(low=0.0, high=1.0, size=(2, 3))
b = np.random.uniform(low=0.0, high=1.0, size=(3))
print(a)
print(b)
print(a * b)

[[0.88902304 0.17727239 0.10803443]
 [0.18322263 0.02756769 0.69577784]]
[0.9130877  0.40445017 0.49629044]
[[0.811756   0.07169785 0.05361646]
 [0.16729833 0.01114976 0.34530789]]


In [14]:
#12
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))
print(a)
print(b)
print(a * b)

[[2 6]
 [5 7]]
[[ 6  6]
 [ 9 10]]
[[12 36]
 [45 70]]


In [15]:
#13
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))
print(a)
print(b)
print(np.dot(a, b))

[[7 1]
 [5 3]]
[[4 5]
 [8 2]]
[[36 37]
 [44 31]]


In [16]:
#14
a = np.random.randint(1, 101, size=(5, 5))
print(a)
print(a.sum())

[[96 24 71 93 43]
 [87 64 37 32 23]
 [29 88 28 57 71]
 [46 94 41 60 63]
 [56 93 57 78 57]]
1488


In [17]:
#15
a = np.random.randint(1, 11, size=(4, 4))
b = np.random.randint(1, 11, size=(4, 4))
print(a)
print(b)
print(a - b)

[[10  3  7  4]
 [ 2  3  3 10]
 [ 6  6  9  9]
 [ 9  7  5 10]]
[[ 7  4  7  3]
 [ 9  8  6  7]
 [ 7  2  8 10]
 [ 2 10  2  2]]
[[ 3 -1  0  1]
 [-7 -5 -3  3]
 [-1  4  1 -1]
 [ 7 -3  3  8]]


In [23]:
#16
a = np.random.uniform(low=0.0, high=1.0, size=(3, 3))
print(a)
b = np.array([sum(a[0, :3]), sum(a[1, :3]), sum(a[2, :3])])
print(b.reshape((3, 1)))

[[0.50613486 0.74712159 0.34470945]
 [0.58693206 0.94316568 0.85095401]
 [0.27929105 0.22751845 0.04508861]]
[[1.5979659 ]
 [2.38105175]
 [0.55189811]]


In [19]:
#17
a = np.random.randint(-11, 11, size=(3, 4))
print(a)
print(np.square(a))


[[  3   0  -8   0]
 [ 10  -5   7   4]
 [ -4   9 -11   1]]
[[  9   0  64   0]
 [100  25  49  16]
 [ 16  81 121   1]]


In [20]:
#18
a = np.random.randint(1, 51, size=(4))
print(a)
print(np.sqrt(a))

[10 25 17 20]
[3.16227766 5.         4.12310563 4.47213595]
